config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index]

  resources :issues, only: [:index, :new, :create, :show] do
    member do
      patch 'change_status', to: 'issues#change_status'
      resources :comments, only: [:create]
    end
  end

  # authenticated :user do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  root 'issues#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  issue_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_issue_id  (issue_id)
#  index_comments_on_user_id   (user_id)
#

class Comment < ActiveRecord::Base
  include MarkdownHelper

  belongs_to :user
  belongs_to :issue, touch: true

  validates :body, presence: true
  validates :user, presence: true
  validates :issue, presence: true
  validates_associated :user, :issue

  def participants
    return [user] unless mentioned_users
    users = mentioned_users << user
    users.flatten.uniq
  end

  def mentioned_users
    @mentioned ||= markdownify_mentioned_user(body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_issue
  before_action :create_new_form

  def create
    @comment_form.submit(comment_params)

    if @comment_form.save
      flash[:success] = '成功添加留言'
      redirect_to issue_path(@issue, anchor: "comment_#{@comment_form.model.id}")
    else
      flash[:error] = @comment_form.errors.full_messages.uniq.join('. ')
      redirect_to @issue
    end
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def create_new_form
    comment = Comment.new(user: current_user, issue: @issue)
    @comment_form = CommentForm.new(comment)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<li>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= div_for(comment) do %>
        <p class="push-bit">
          <strong>@<%= comment.user.username %></strong> 在 <strong><%= local_time_ago(comment.created_at) %></strong> 留言：
        </p>
        <%= markdownify(comment.body) %>
      <% end %>
      <hr>
    </div>
  </div>
</li>

app/views/comments/_form.html.erb
<%= simple_form_for CommentForm.new(Comment.new), url: comments_path(@issue) do |f| %>

<%= f.input :body, label: false, as: :text, required: true, input_html: { rows: 8, 'data-at-mention': 'autocomplete' } %>

<div class="form-actions text-right">
  <%= f.button :button, class: 'btn btn-lg btn-primary', data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> loading..." } %>
</div>
<% end %>