config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index]

  resources :issues, only: [:index, :new, :create, :show] do
    member do
      patch 'change_status', to: 'issues#change_status'
      resources :comments, only: [:create]
    end
  end

  # authenticated :user do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  root 'issues#index'
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  status     :integer          default(0), not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_issues_on_status   (status)
#  index_issues_on_title    (title) UNIQUE
#  index_issues_on_user_id  (user_id)
#

class Issue < ActiveRecord::Base
  enum status: [:open, :closed, :urgent]

  belongs_to :user, touch: true
  has_many :comments, dependent: :destroy

  auto_strip_attributes :title

  validates :title, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: { in: statuses }, allow_blank: true
  validates :user, presence: true
  validates_associated :user

  def participants
    comments.collect(&:participants).flatten.uniq
  end

  def last_commenter_username
    comments.last.user.username
  end

  def last_commenter
    comments.last.user
  end

  def last_commented_at
    comments.last.created_at
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :create_new_form, only: [:new, :create]
  before_action :set_counts, only: [:index, :new, :show]

  def index
    issue_scrope = %w(all open closed).include?(params[:scope]) ? params[:scope] : 'open'

    @issues = Issue.send(issue_scrope).includes(comments: :user).order(updated_at: :desc)
  end

  def new
  end

  def create
    @issue_form.submit(issue_params)
    @issue_form.comments.first.user = current_user
    @issue_form.comments.first.issue = @issue_form.model

    if @issue_form.save
      flash[:success] = '成功添加话题'
      redirect_to @issue_form
    else
      flash[:error] = @issue_form.errors.full_messages.uniq.join('. ')
      render :new
    end
  end

  def show
    @issue = Issue.includes(comments: :user).find(params[:id])
  end

  def change_status
    @issue = Issue.find(params[:id])
    if @issue.update(status: issue_status_params)
      flash[:success] = '成功修改话题'
    else
      flash[:error] = @issue.errors.full_messages.uniq.join('. ')
    end
    redirect_to @issue
  end

  private

  def create_new_form
    issue = Issue.new(user: current_user)
    @issue_form = IssueForm.new(issue)
  end

  def issue_params
    params.require(:issue).permit(:title, comments_attributes: [:body])
  end

  def issue_status_params
    params.require(:status)
  end

  def set_counts
    @all_count = Issue.all.size
    @open_count = Issue.open.size
    @closed_count = Issue.closed.size
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def status_label(status)
    "<span class='label label-#{status_color_class(status)}'>#{status.titleize}</span>".html_safe
  end

  def status_color_class(status)
    case status.downcase
    when 'urgent'
      'danger'
    when 'closed'
      'default'
    else
      'info'
    end
  end
end

app/views/issues/_form.html.erb
<%= simple_form_for @issue_form, wrapper: :vertical_form do |f| %>

<%= f.input :title, label: Issue.human_attribute_name('title'), required: true, autofocus: true %>

<%= f.simple_fields_for :comments do |c| %>
<%= c.input :body, as: :text, required: true, input_html: { rows: 8, 'data-at-mention': 'autocomplete' } %>
<% end %>

<div class="form-group form-actions text-right">
  <%= f.button :button, class: 'btn btn-lg btn-primary', data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> loading..." } %>
</div>

<% end %>

app/views/issues/_issue.html.erb
<tr>
  <td class="text-center">#<%= issue.id %></td>
  <td><%= status_label(issue.status) %></td>
  <td>
    <strong><%= link_to issue.title, issue %></strong><br>
    <span class="text-muted"><strong><%= issue.last_commenter_username %></strong> 在 <%= local_time_ago(issue.last_commented_at) %></span>
  </td>
  <td class="text-center"><span class="badge"><%= issue.comments.size - 1 %></span></td>
</tr>

app/views/issues/_menu.html.erb
<!-- Menu Block -->
<div class="block full">
  <!-- Menu Title -->
  <div class="block-title clearfix">
    <h2>话题管理</h2>
  </div>
  <!-- END Menu Title -->

  <!-- Menu Content -->
  <ul class="nav nav-pills nav-stacked">
    <li id="all-issues">
      <a href="/issues/?scope=all">
        <span class="badge pull-right"><%= @all_count %></span>
        <i class="fa fa-fw fa-ticket icon-push"></i> <strong>所有</strong>
      </a>
    </li>
    <li id="open-issues">
      <a href="/issues/?scope=open">
        <span class="badge pull-right"><%= @open_count %></span>
        <i class="fa fa-fw fa-folder-open-o icon-push"></i> <strong><%= Issue.human_attribute_name('status.open') %></strong>
      </a>
    </li>
    <li id="closed-issues">
      <a href="/issues/?scope=closed">
        <span class="badge pull-right"><%= @closed_count %></span>
        <i class="fa fa-fw fa-folder-o icon-push"></i> <strong><%= Issue.human_attribute_name('status.closed') %></strong>
      </a>
    </li>
    <li id="new-issues">
      <%= link_to '新增话题', new_issue_path, class: 'btn btn-effect-ripple btn-default' %>
    </li>
  </ul>
  <!-- END Menu Content -->
  </div>
  <!-- END Menu Block -->

app/views/issues/_temp_paginsation.html.erb
<div class="text-center">
  <ul class="pagination">
    <li class="disabled"><a href="javascript:void(0)"><i class="fa fa-chevron-left"></i></a></li>
    <li class="active"><a href="javascript:void(0)">1</a></li>
    <li><a href="javascript:void(0)">2</a></li>
    <li><a href="javascript:void(0)">3</a></li>
    <li><a href="javascript:void(0)"><i class="fa fa-chevron-right"></i></a></li>
  </ul>
</div>

app/views/issues/index.html.erb
<%= content_for :header_title, Issue.model_name.human %>

<!-- Issues Content -->
<div class="row">
  <div class="col-md-4 col-lg-3">

    <%= render 'issues/menu' %>

  </div>
  <div class="col-md-8 col-lg-9">
    <!-- Issues Block -->
    <div class="block">
      <!-- Issues Title -->
      <div class="block-title clearfix">
        <h2>话题列表</h2>
      </div>
      <!-- END Issues Title -->

        <!-- Issues List -->
        <div id="issues-list">
          <div class="block-content-full">
            <div class="table-responsive remove-margin-bottom">
              <table class="table table-striped table-vcenter remove-margin-bottom">
                <thead>
                  <tr>
                    <th class="text-center">编号</th>
                    <th><%= Issue.human_attribute_name('status') %></th>
                    <th><%= Issue.human_attribute_name('title') %></th>
                    <th class="text-center"><i class="fa fa-comments"></i></th>
                  </tr>
                </thead>
                <tbody>
                  <%= render @issues %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <!-- END Issues List -->
    </div>
    <!-- END Issues Block -->
  </div>
</div>
<!-- END Issues Content -->

app/views/issues/new.html.erb
<%= content_for :header_title, '新增话题' %>

<!-- Get Started Block -->
<div class="block full">
  <!-- Get Started Title -->
  <div class="block-title">
    <h2>新增话题</h2>
  </div>
  <!-- END Get Started Title -->


  <!-- Get Started Content -->
  <%= render 'issues/form' %>

  <!-- END Get Started Content -->
</div>
<!-- END Get Started Block -->

app/views/issues/show.html.erb
<%= content_for :header_title, "#{@issue.title} ##{@issue.id}" %>


<!-- Issue Content -->
<div class="row">
  <div class="col-md-4 col-lg-3">

    <%= render 'issues/menu' %>

  </div>
  <div class="col-md-8 col-lg-9">
    <!-- Issue Block -->
    <div class="block ">
      <!-- Issue Title -->
      <div class="block-title clearfix">
        <h2>话题 #<%= @issue.id %></h2>
      </div>
      <!-- END Issue Title -->


      <div class="row">
        <div class="col-xs-12">
          <!-- Issue Single -->
      <div id="issues-single">

        <div class="btn-group pull-right">
          <a href="javascript:void(0)" data-toggle="dropdown" class="btn btn-<%= status_color_class(@issue.status) %> dropdown-toggle" aria-expanded="false"><%= Issue.human_attribute_name('status') %>: <%= @issue.status.titleize %> <span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-menu-right">
            <% unless @issue.open? %>
            <li>
              <%= link_to "<i class='fa fa-folder-open pull-right'></i>
              #{Issue.human_attribute_name('status.open')}".html_safe, change_status_issue_path(status: :open), method: :patch %>
            </li>
            <% end %>
            <% unless @issue.closed? %>
            <li>
              <%= link_to "<i class='fa fa-folder pull-right'></i>
              #{Issue.human_attribute_name('status.closed')}".html_safe, change_status_issue_path(status: :closed), method: :patch %>
            </li>
            <% end %>
          </ul>
          </div>

          <h2><%= @issue.title %></h2>
          <h4>issue #<%= @issue.id %></h4>

        <hr>
        <ul class="media-list media-feed push">
          <!-- Comments -->
          <%= render @issue.comments %>

          <!-- Reply -->
          <li>
            <div class="row">
              <div class="col-md-10 col-md-offset-1">

                <%= render 'comments/form' %>
                    </div>
                  </div>
                </li>

          <!-- END Replies -->
        </ul>
      </div>
      <!-- END Issue Single -->
    </div>
    </div>
    </div>
    <!-- END Issue Details -->
  </div>
  <!-- END col -->
</div>
<!-- END Issue Content -->