config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index]

  resources :issues, only: [:index, :new, :create, :show] do
    member do
      patch 'change_status', to: 'issues#change_status'
      resources :comments, only: [:create]
    end
  end

  # authenticated :user do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  root 'issues#index'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <!-- Left Header Navigation -->
  <ul class="nav navbar-nav-custom">
    <!-- Main Sidebar Toggle Button -->
    <li>
      <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');this.blur();">
        <i class="fa fa-ellipsis-v fa-fw animation-fadeInRight" id="sidebar-toggle-mini"></i>
        <i class="fa fa-bars fa-fw animation-fadeInRight" id="sidebar-toggle-full"></i>
      </a>
    </li>
    <!-- END Main Sidebar Toggle Button -->
  </ul>
  <!-- END Left Header Navigation -->

  <!-- Right Header Navigation -->
  <ul class="nav navbar-nav-custom pull-right">
    <!-- Search Form -->
    <li>
      <form action="###" method="post" class="navbar-form-custom" role="search">
        <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Search Not Working..">
      </form>
    </li>
    <!-- END Search Form -->

    <li>
      <%= link_to "@#{current_user.username}", edit_user_registration_path %>
    </li>

  </ul>
  <!-- END Right Header Navigation -->
</header>
<!-- END Header -->

app/views/layouts/_messages.html.erb
<% unless flash.blank? %>
  <!-- Flash Messages -->
  <% toastr_options = 'toastr.options = {
    "closeButton": false,
    "debug": false,
    "newestOnTop": true,
    "progressBar": true,
    "positionClass": "toast-bottom-full-width",
    "preventDuplicates": true
  };' %>
  <%= javascript_tag  toastr_options %>

  <% flash.each do |key, value| %>
    <% if value.is_a?(String) %>
      <% context = toastr_context(key) %>
      <% e_value = escape_javascript(value) %>
      <% toastr_sctipt = "toastr['#{context}']('#{e_value}');" %>
     <%= javascript_tag toastr_sctipt %>
      <%= javascript_tag  "console.log('get');" %>
   <% end %>
 <% end %>
 <!-- End Flash Messages -->
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Main Sidebar -->
<div id="sidebar">
  <!-- Sidebar Brand -->
  <div id="sidebar-brand" class="themed-background">
    <%= link_to '<span class="sidebar-nav-mini-hide"><strong>Glamorous</strong></span>'.html_safe, root_path, class: 'sidebar-title' %>
  </div>
  <!-- END Sidebar Brand -->

  <!-- Wrapper for scrolling functionality -->
  <div id="sidebar-scroll">
    <!-- Sidebar Content -->
    <div class="sidebar-content">
      <!-- Sidebar Navigation -->
      <ul class="sidebar-nav">
        <%= render 'layouts/sidebar_links' %>
      </ul>
      <!-- END Sidebar Navigation -->

    </div>
    <!-- END Sidebar Content -->
  </div>
  <!-- END Wrapper for scrolling functionality -->

  <!-- Sidebar Extra Info -->
  <div id="sidebar-extra-info" class="sidebar-content sidebar-nav-mini-hide">
    <div class="text-center">
      <small>Crafted with <i class="fa fa-heart text-danger"></i> by <a href="mailto:tangrufus@gmail.com" target="_blank">Tang Rufus</a></small>
      <br>
      <small><span id="year-copy"></span> &copy; <a href="https://www.pinot.hk" target="_blank">Pinot</a></small>
    </div>
  </div>
  <!-- END Sidebar Extra Info -->
</div>
<!-- END Main Sidebar -->

app/views/layouts/_sidebar_links.html.erb
<li>
    <%= link_to '<i class="fa fa-ticket sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">话题</span>'.html_safe, issues_path %>
</li>
<li>
    <%= link_to '<i class="gi gi-group sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">用户</span>'.html_safe, users_path %>
</li>
<li>
    <%= link_to '<i class="gi gi-keys sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">密码</span>'.html_safe, edit_user_registration_path %>
</li>
<li>
    <%= link_to '<i class="hi hi-off sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">登出</span>'.html_safe, destroy_user_session_path, method: :delete %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>Glamorous</title>

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css' %>

  <%= jquery_include_tag :cloudflare %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>

  <%= javascript_include_tag :modernizr %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %>">

  <div id="page-container" class="header-fixed-top sidebar-visible-lg-full">

    <%= render 'layouts/sidebar' %>

    <!-- Main Container -->
    <div id="main-container">

      <%= render 'layouts/header' %>

      <!-- Page content -->
      <div id="page-content">

        <% if content_for?(:header_title) %>
        <!-- Page Header -->
        <div class="content-header">
          <div class="row">
            <div class="col-sm-6">
              <div class="header-section">
                <h1><%= yield(:header_title) %></h1>
              </div>
            </div>
          </div>
        </div>
        <!-- END Page Header -->
        <% end %>

        <%= render 'layouts/messages' %>
        <%= yield %>

      </div>
      <!-- END Page Content -->
    </div>
    <!-- END Main Container -->
  </div>
  <!-- END Page Container -->
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>Glamorous</title>

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css' %>

  <%= jquery_include_tag :cloudflare %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>

  <%= javascript_include_tag :modernizr %>

  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Login Container -->
  <div id="login-container">
    <!-- Login Header -->
    <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
      <%= link_to '<strong>Glamorous</strong>'.html_safe, root_path %>
    </h1>
    <!-- END Login Header -->

    <!-- Login Block -->
    <div class="block animation-fadeInQuickInv">
      <!-- Login Title -->
      <div class="block-title">
        <h2><%= yield(:title) %></h2>
      </div>
      <!-- END Login Title -->

      <%= render "layouts/messages" %>

      <%= yield %>

    </div>
    <!-- END Login Block -->

    <!-- Footer -->
    <footer class="text-muted text-center animation-pullUp">
      <%= render "devise/shared/links" %>
      <br />
      <br />
      <small>Crafted with <i class="fa fa-heart text-danger"></i> by <a href="mailto:tangrufus@gmail.com" target="_blank">Tang Rufus</a></small>
      <br>
      <small><span id="year-copy"></span> &copy; <a href="https://www.pinot.hk" target="_blank">Pinot</a></small>
    </footer>
    <!-- END Footer -->
  </div>
  <!-- END Login Container -->

</body>
</html>